def mmw_set_config(configdict: dict) -> int: ...
def mmw_init(ip_addr: str = "192.168.33.180", port: int = 5001) -> int: ...
def mmw_arming_tda(capture_path: str) -> int: ...
def mmw_start_frame() -> int: ...
def mmw_stop_frame() -> int: ...
def mmw_dearming_tda() -> int: ...
